version: 2
updates:
    # Maintain dependencies for GitHub Actions.
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 0

    # Maintain dependencies for Composer
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase-if-necessary
